from .recmed_ui import Ui_RecMedWindow
from .openeddockwidget_ui import Ui_OpenedDock
from .documentwidget_ui import Ui_DocumentWidget
from .docmetadatawidget_ui import Ui_DocMetadataWidget
from .contenttemplateeditor_ui import Ui_ContentTemplateEditor